name: CI

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:

  go-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v4
      with:
        go-version-file: 'go.mod'
    - run: go build -v ./...

  go-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v4
      with:
        go-version-file: 'go.mod'
    - run: go test -v ./...

  go-fmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v4
      with:
        go-version-file: 'go.mod'
    - run: go fmt ./...
    - run: git diff --exit-code

  cram:
    runs-on: ubuntu-latest
    needs: ["go-build", "go-test"]
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v4
      with:
        go-version-file: 'go.mod'
    - run: go install -v .
    - run: pip install cram
    - run: cram test.t
